export const NOM_ETABLISSEMENT = "IFSI du CHAM";
export const TODAY = new Date().toISOString().split("T")[0];

export const RESPONSABLES = [
  "RETARDATO Clementine (Directrice des soins)",
  "TZOTZIS Christelle (Coordinatrice pedagogique)",
  "AUBRY Guillaume (Formateur 1A)",
  "BRASSINE Deborah (Formatrice 3A)",
  "CHARLES Valerie (Formatrice 2A)",
  "LEROY Sandra (Formatrice 1A)",
  "HEGO Coralie (Formatrice 2A)",
  "KERBIDI Julie (Formatrice 1A)",
  "LAFONT Laura (Formatrice 1A)",
  "MARTIN Audrey (Formatrice 1A - Ref. ABS)",
  "LA GUMINA Samantha (Formatrice 3A)",
  "MONTAINT Sophie (Formatrice 3A)",
  "SONVEAU Marie-Cecile (Formatrice 3A)",
  "JOUBAUD Virginie (Formatrice 2A)",
  "KRYLYSCHIN Virginie (Formatrice 2A)",
  "CARRE Joris (Documentaliste)",
  "QUAAK Jan (Referent TICE)",
  "HURTER Nathalie (Secretaire)",
  "MAITREHUT Irene (Secretaire)",
  "MELITO SAIHI Melanie (Secretaire)",
  "RATTEZ Eva (Secretaire)",
];

export const DEFAULT_CRITERES = [
  { id: 1, num: "Indicateur 1", critere: 1, titre: "Information sur les prestations", responsables: [], delai: TODAY, statut: "non-evalue", notes: "", 
    attendus: "Démontrer que l'information (prérequis, objectifs, durée, modalités, tarifs, contacts, accessibilité handicap) est accessible, exhaustive et actualisée.", 
    preuves: "Site web de l'IFSI, plaquette, livret d'accueil, supports de communication, CGV..." },
  { id: 2, num: "Indicateur 2", critere: 1, titre: "Indicateurs de résultats", responsables: [], delai: TODAY, statut: "non-evalue", notes: "", 
    attendus: "Démontrer que les indicateurs de performance (taux de réussite, d'abandon, d'insertion) sont calculés, diffusés et mis à jour.", 
    preuves: "Site internet de l'IFSI (page chiffres clés), affichage, bilan d'activité annuel..." },
  { id: 3, num: "Indicateur 3", critere: 1, titre: "Obtention de la certification", responsables: [], delai: TODAY, statut: "non-evalue", notes: "", 
    attendus: "Démontrer que les taux d'obtention de la certification (DE Infirmier) sont diffusés si la formation est certifiante.", 
    preuves: "Tableaux de bord des diplômés, site internet, rapports de jury du DE..." },

  { id: 4, num: "Indicateur 4", critere: 2, titre: "Analyse du besoin", responsables: [], delai: TODAY, statut: "non-evalue", notes: "", 
    attendus: "Démontrer qu'il existe une analyse des besoins du bénéficiaire ou du commanditaire en lien avec la prestation.", 
    preuves: "Compte-rendu d'entretien, grilles d'analyse des besoins, cahier des charges du CH..." },
  { id: 5, num: "Indicateur 5", critere: 2, titre: "Objectifs de la prestation", responsables: [], delai: TODAY, statut: "non-evalue", notes: "", 
    attendus: "Démontrer que les objectifs sont définis, évaluables et opérationnels.", 
    preuves: "Ingénierie de la formation, fiches modules (UE), programme pédagogique détaillé..." },
  { id: 6, num: "Indicateur 6", critere: 2, titre: "Contenus et mise en oeuvre", responsables: [], delai: TODAY, statut: "non-evalue", notes: "", 
    attendus: "Démontrer que les contenus et les modalités de mise en œuvre sont adaptés aux objectifs.", 
    preuves: "Plannings, supports de cours, scénarios de simulation en santé, déroulés pédagogiques..." },
  { id: 7, num: "Indicateur 7", critere: 2, titre: "Adéquation aux exigences de certification", responsables: [], delai: TODAY, statut: "non-evalue", notes: "", 
    attendus: "Démontrer que les contenus sont en adéquation avec le référentiel de certification visé.", 
    preuves: "Matrice de correspondance avec le référentiel infirmier (Annexe de l'arrêté de 2009)..." },
  { id: 8, num: "Indicateur 8", critere: 2, titre: "Positionnement à l'entrée", responsables: [], delai: TODAY, statut: "non-evalue", notes: "", 
    attendus: "Démontrer qu'il existe une évaluation initiale des acquis et que le parcours est adapté en conséquence.", 
    preuves: "Tests de positionnement, bilans de compétences, entretiens d'admission, dispenses de scolarité..." },

  { id: 9, num: "Indicateur 9", critere: 3, titre: "Conditions d'implication des publics", responsables: [], delai: TODAY, statut: "non-evalue", notes: "", 
    attendus: "Démontrer que l'étudiant est informé des conditions de déroulement de la formation avant qu'elle ne débute.", 
    preuves: "Règlement intérieur de l'IFSI, livret de stage, convocations, charte de l'étudiant..." },
  { id: 10, num: "Indicateur 10", critere: 3, titre: "Adaptation de la prestation", responsables: [], delai: TODAY, statut: "non-evalue", notes: "", 
    attendus: "Démontrer que la prestation et les modalités d'accompagnement sont adaptées au profil du bénéficiaire.", 
    preuves: "Aménagements pour PSH, parcours partiels (AS vers IDE), tutorat spécifique..." },
  { id: 11, num: "Indicateur 11", critere: 3, titre: "Évaluation de l'atteinte des objectifs", responsables: [], delai: TODAY, statut: "non-evalue", notes: "", 
    attendus: "Démontrer que les acquis sont évalués en cours et fin de prestation.", 
    preuves: "Partiels, grilles d'évaluation, portfolio de stage, CAC (Commission d'Attribution des Crédits)..." },
  { id: 12, num: "Indicateur 12", critere: 3, titre: "Mesures pour favoriser l'engagement", responsables: [], delai: TODAY, statut: "non-evalue", notes: "", 
    attendus: "Démontrer que des actions sont mises en œuvre pour prévenir les ruptures de parcours.", 
    preuves: "Suivi des absences, bilans de suivi pédagogique (suivi de promo), relances, entretiens..." },
  { id: 13, num: "Indicateur 13", critere: 3, titre: "Alternance et articulation des apprentissages", responsables: [], delai: TODAY, statut: "non-evalue", notes: "", 
    attendus: "(Spécifique Apprentissage) Démontrer l'articulation entre l'OFA et l'entreprise.", 
    preuves: "Carnet de liaison, visites de stage, réunions maîtres d'apprentissage..." },
  { id: 14, num: "Indicateur 14", critere: 3, titre: "Accompagnement socio-professionnel", responsables: [], delai: TODAY, statut: "non-evalue", notes: "", 
    attendus: "(Spécifique Apprentissage) Démontrer l'accompagnement éducatif et socio-professionnel.", 
    preuves: "Assistante sociale, réunions d'information, dispositif d'aide au logement..." },
  { id: 15, num: "Indicateur 15", critere: 3, titre: "Droits et devoirs de l'apprenti", responsables: [], delai: TODAY, statut: "non-evalue", notes: "", 
    attendus: "(Spécifique Apprentissage) Démontrer que l'apprenti est informé de ses droits/devoirs.", 
    preuves: "Livret d'accueil CFA, réunions de rentrée, émargement règlement intérieur..." },
  { id: 16, num: "Indicateur 16", critere: 3, titre: "Conditions de présentation aux examens", responsables: [], delai: TODAY, statut: "non-evalue", notes: "", 
    attendus: "Démontrer que les conditions d'examen sont respectées.", 
    preuves: "Convocations aux épreuves, procès-verbaux d'examen, attestations de réussite..." },

  { id: 17, num: "Indicateur 17", critere: 4, titre: "Moyens humains et techniques", responsables: [], delai: TODAY, statut: "non-evalue", notes: "", 
    attendus: "Démontrer que les moyens mis à disposition sont en adéquation avec la formation.", 
    preuves: "Locaux conformes, salles de simulation, matériel médical pédagogique, ENT, ordinateurs..." },
  { id: 18, num: "Indicateur 18", critere: 4, titre: "Coordination des acteurs", responsables: [], delai: TODAY, statut: "non-evalue", notes: "", 
    attendus: "Démontrer l'existence d'une fonction de coordination des intervenants (internes/externes).", 
    preuves: "Réunions d'équipe pédagogique, organigramme de l'IFSI, plannings d'intervention..." },
  { id: 19, num: "Indicateur 19", critere: 4, titre: "Ressources pédagogiques", responsables: [], delai: TODAY, statut: "non-evalue", notes: "", 
    attendus: "Démontrer que l'apprenant a accès aux ressources pédagogiques adéquates.", 
    preuves: "Accès CDI/bibliothèque, plateforme e-learning (Moodle/ENT), bibliographies..." },
  { id: 20, num: "Indicateur 20", critere: 4, titre: "Personnel dédié à la mobilité", responsables: [], delai: TODAY, statut: "non-evalue", notes: "", 
    attendus: "Démontrer l'existence d'un référent mobilité nationale et internationale.", 
    preuves: "Nomination du référent Erasmus+, charte Erasmus+, partenariats internationaux..." },

  { id: 21, num: "Indicateur 21", critere: 5, titre: "Compétences des intervenants", responsables: [], delai: TODAY, statut: "non-evalue", notes: "", 
    attendus: "Démontrer que les compétences des formateurs (internes/externes) sont évaluées et adéquates.", 
    preuves: "CV mis à jour, diplômes (Cadre de Santé, Masters...), titres, contrats de vacation..." },
  { id: 22, num: "Indicateur 22", critere: 5, titre: "Maintien et développement des compétences", responsables: [], delai: TODAY, statut: "non-evalue", notes: "", 
    attendus: "Démontrer la mise en œuvre d'un plan de développement des compétences pour l'équipe.", 
    preuves: "Plan de formation du CHAM, attestations de formation des formateurs, DU, DU Simulation..." },

  { id: 23, num: "Indicateur 23", critere: 6, titre: "Veille légale et réglementaire", responsables: [], delai: TODAY, statut: "non-evalue", notes: "", 
    attendus: "Démontrer la réalisation d'une veille sur l'évolution de la législation (formation et santé) et son exploitation.", 
    preuves: "Abonnements revues juridiques, circulaires ARS/Ministère, traces de modification des processus..." },
  { id: 24, num: "Indicateur 24", critere: 6, titre: "Veille métiers et compétences", responsables: [], delai: TODAY, statut: "non-evalue", notes: "", 
    attendus: "Démontrer la réalisation d'une veille sur l'évolution des métiers de la santé et l'adaptation des formations.", 
    preuves: "Participation aux instances du CH, revues infirmières (Soins, Objectif Soins), participation CEFIEC..." },
  { id: 25, num: "Indicateur 25", critere: 6, titre: "Veille pédagogique et technologique", responsables: [], delai: TODAY, statut: "non-evalue", notes: "", 
    attendus: "Démontrer la réalisation d'une veille sur les innovations pédagogiques (simulation, e-learning...).", 
    preuves: "Participation à des congrès, salons (SantExpo, congrès simulation), abonnements..." },
  { id: 26, num: "Indicateur 26", critere: 6, titre: "Mobilisation d'un réseau Handicap", responsables: [], delai: TODAY, statut: "non-evalue", notes: "", 
    attendus: "Démontrer que l'organisme mobilise un réseau d'experts pour l'accueil des PSH.", 
    preuves: "Annuaire des partenaires handicap (AGEFIPH, MDPH, Cap Emploi), nomination du Référent Handicap..." },
  { id: 27, num: "Indicateur 27", critere: 6, titre: "Pilotage de la sous-traitance", responsables: [], delai: TODAY, statut: "non-evalue", notes: "", 
    attendus: "Démontrer que les sous-traitants respectent le référentiel national qualité.", 
    preuves: "Contrats de sous-traitance avec clauses Qualiopi, grilles d'évaluation des intervenants externes..." },
  { id: 28, num: "Indicateur 28", critere: 6, titre: "Périodes de formation en situation de travail", responsables: [], delai: TODAY, statut: "non-evalue", notes: "", 
    attendus: "Démontrer que les stages en milieu clinique sont organisés, suivis et analysés.", 
    preuves: "Conventions de stage, livrets d'accueil en service, visites de stage, réunions tuteurs/maîtres de stage..." },
  { id: 29, num: "Indicateur 29", critere: 6, titre: "Insertion professionnelle (Apprentissage)", responsables: [], delai: TODAY, statut: "non-evalue", notes: "", 
    attendus: "(Spécifique Apprentissage) Démontrer la mise en place d'actions favorisant l'insertion.", 
    preuves: "Forums de recrutement du CHAM, ateliers CV, rencontres avec les DRH..." },

  { id: 30, num: "Indicateur 30", critere: 7, titre: "Recueil des appréciations", responsables: [], delai: TODAY, statut: "non-evalue", notes: "", 
    attendus: "Démontrer que les appréciations (étudiants, formateurs, lieux de stage, financeurs) sont recueillies.", 
    preuves: "Questionnaires de satisfaction (fin d'UE, fin d'année), bilans de stage, comptes-rendus de conseils pédagogiques..." },
  { id: 31, num: "Indicateur 31", critere: 7, titre: "Traitement des réclamations et aléas", responsables: [], delai: TODAY, statut: "non-evalue", notes: "", 
    attendus: "Démontrer qu'il existe une procédure de traitement des difficultés, abandons et réclamations.", 
    preuves: "Registre des réclamations, procédure de traitement affichée, fiches d'évènements indésirables..." },
  { id: 32, num: "Indicateur 32", critere: 7, titre: "Amélioration continue", responsables: [], delai: TODAY, statut: "non-evalue", notes: "", 
    attendus: "Démontrer qu'une démarche d'amélioration continue est mise en œuvre suite aux évaluations et aléas.", 
    preuves: "Plan d'actions qualité, revues de direction, comptes-rendus d'instance de pilotage qualité..." },
];

export const CRITERES_LABELS = {
  1: { label: "Information des publics",         color: "#1d4ed8" },
  2: { label: "Identification des objectifs",    color: "#6d28d9" },
  3: { label: "Adaptation aux publics",          color: "#be185d" },
  4: { label: "Adéquation des moyens",           color: "#b45309" },
  5: { label: "Qualification des intervenants",  color: "#065f46" },
  6: { label: "Inscription dans l'environnement",color: "#0e7490" },
  7: { label: "Recueil et prise en compte",      color: "#b91c1c" },
};

export const STATUT_CONFIG = {
  "non-evalue":   { label: "Non evalué",   color: "#6b7280", bg: "#f3f4f6", border: "#d1d5db" },
  "conforme":     { label: "Conforme",     color: "#065f46", bg: "#d1fae5", border: "#6ee7b7" },
  "en-cours":     { label: "En cours",     color: "#92400e", bg: "#fef3c7", border: "#fcd34d" },
  "non-conforme": { label: "Non conforme", color: "#991b1b", bg: "#fee2e2", border: "#fca5a5" },
};
